export const SEERAH_CATEGORY_KEY = "prophet-muhammad-100-de";
export const SEERAH_CATEGORY_NAME = "100 Fragen über den Propheten Muhammad ﷺ";

export const SEERAH_QUESTIONS = [
  [1,"Wo wurde der Prophet Muhammad ﷺ geboren?",["Mekka","Medina","Taif"],"Mekka","easy",5,"Der Prophet Muhammad ﷺ wurde in Mekka geboren."],
  [2,"In welchem Jahr wurde der Prophet Muhammad ﷺ geboren?",["Im Jahr des Elefanten","Im Jahr der Hidschra","Im Jahr von Badr"],"Im Jahr des Elefanten","medium",10,"Sein Geburtsjahr ist als Jahr des Elefanten bekannt."],
  [3,"Wie hieß der Vater des Propheten Muhammad ﷺ?",["Abdullah","Abu Talib","Hamza"],"Abdullah","easy",5,"Der Vater des Propheten ﷺ hieß Abdullah."],
  [4,"Wie hieß die Mutter des Propheten Muhammad ﷺ?",["Amina","Khadidscha","Fatima"],"Amina","easy",5,"Die Mutter des Propheten ﷺ hieß Amina bint Wahb."],
  [5,"Zu welchem Stamm gehörte der Prophet Muhammad ﷺ?",["Quraisch","Aus","Khazradsch"],"Quraisch","easy",5,"Der Prophet ﷺ gehörte zum Stamm der Quraisch."],
  [6,"Wie hieß der Großvater des Propheten ﷺ?",["Abd al-Muttalib","Abu Bakr","Bilal"],"Abd al-Muttalib","medium",10,"Sein Großvater hieß Abd al-Muttalib."],
  [7,"Wie hieß der Onkel, der den Propheten ﷺ unterstützte?",["Abu Talib","Abu Lahab","Abu Sufyan"],"Abu Talib","medium",10,"Abu Talib nahm den Propheten ﷺ nach dem Tod seines Großvaters auf."],
  [8,"Wie alt war der Prophet ﷺ, als seine Mutter starb?",["6 Jahre","10 Jahre","15 Jahre"],"6 Jahre","medium",10,"Der Prophet ﷺ war etwa sechs Jahre alt, als seine Mutter starb."],
  [9,"Wie hieß die Amme des Propheten ﷺ?",["Halima Sa'diyya","Aischa","Umm Salama"],"Halima Sa'diyya","medium",10,"Halima Sa'diyya war die bekannte Amme des Propheten ﷺ."],
  [10,"Welchen Beinamen hatte der Prophet ﷺ vor dem Prophetentum?",["Al-Amin","Al-Faruq","Asadullah"],"Al-Amin","easy",5,"Er wurde Al-Amin genannt, weil er vertrauenswürdig war."],
  [11,"Was bedeutet Al-Amin?",["Der Vertrauenswürdige","Der Starke","Der Reiche"],"Der Vertrauenswürdige","easy",5,"Al-Amin bedeutet der Vertrauenswürdige."],
  [12,"Wie alt war der Prophet ﷺ bei seiner Heirat mit Khadidscha?",["25 Jahre","30 Jahre","40 Jahre"],"25 Jahre","medium",10,"Der Prophet ﷺ war 25 Jahre alt, als er Khadidscha heiratete."],
  [13,"Wie hieß die erste Ehefrau des Propheten ﷺ?",["Khadidscha","Aischa","Hafsa"],"Khadidscha","easy",5,"Khadidscha رضي الله عنها war seine erste Ehefrau."],
  [14,"Wie alt war der Prophet ﷺ, als er die erste Offenbarung erhielt?",["40 Jahre","30 Jahre","50 Jahre"],"40 Jahre","easy",5,"Er war 40 Jahre alt, als die erste Offenbarung kam."],
  [15,"In welcher Höhle erhielt der Prophet ﷺ die erste Offenbarung?",["Hira","Thaur","Uhud"],"Hira","easy",5,"Die erste Offenbarung kam in der Höhle Hira."],
  [16,"Welcher Engel brachte dem Propheten ﷺ die Offenbarung?",["Dschibril","Mikail","Israfil"],"Dschibril","easy",5,"Engel Dschibril عليه السلام brachte die Offenbarung."],
  [17,"Was waren die ersten offenbarten Worte?",["Lies!","Bete!","Wandere aus!"],"Lies!","medium",10,"Die erste Offenbarung begann mit dem Wort 'Lies!'"],
  [18,"Wie viele Jahre dauerte die Offenbarung ungefähr?",["23 Jahre","10 Jahre","40 Jahre"],"23 Jahre","medium",10,"Die Offenbarung dauerte ungefähr 23 Jahre."],
  [19,"Wie hieß der erste Mann, der den Islam annahm?",["Abu Bakr","Umar","Ali"],"Abu Bakr","medium",10,"Abu Bakr رضي الله عنه gehörte zu den ersten Muslimen."],
  [20,"Wie hieß der erste Junge, der den Islam annahm?",["Ali","Zaid","Bilal"],"Ali","medium",10,"Ali ibn Abi Talib رضي الله عنه nahm den Islam als Junge an."],
  [21,"Wie hieß der erste Muezzin im Islam?",["Bilal","Salman","Musab"],"Bilal","easy",5,"Bilal ibn Rabah رضي الله عنه war der erste Muezzin."],
  [22,"Wohin wanderten einige Muslime zuerst aus?",["Abessinien","Persien","Syrien"],"Abessinien","hard",15,"Einige Muslime wanderten zuerst nach Abessinien aus."],
  [23,"Warum wanderten Muslime nach Abessinien aus?",["Wegen Verfolgung","Wegen Handel","Wegen Krieg"],"Wegen Verfolgung","medium",10,"Sie suchten Schutz vor Verfolgung in Mekka."],
  [24,"Wie heißt die Auswanderung von Mekka nach Medina?",["Hidschra","Isra","Badr"],"Hidschra","easy",5,"Die Auswanderung nach Medina heißt Hidschra."],
  [25,"Mit wem wanderte der Prophet ﷺ nach Medina aus?",["Abu Bakr","Umar","Hamza"],"Abu Bakr","medium",10,"Abu Bakr رضي الله عنه begleitete den Propheten ﷺ bei der Hidschra."],
  [26,"In welcher Höhle versteckten sich der Prophet ﷺ und Abu Bakr?",["Thaur","Hira","Badr"],"Thaur","medium",10,"Sie versteckten sich in der Höhle Thaur."],
  [27,"Wie hieß die Stadt Medina vor der Hidschra?",["Yathrib","Kufa","Basra"],"Yathrib","medium",10,"Medina hieß früher Yathrib."],
  [28,"Was baute der Prophet ﷺ zuerst in Medina?",["Eine Moschee","Einen Palast","Einen Markt"],"Eine Moschee","easy",5,"In Medina wurde eine Moschee gebaut."],
  [29,"Wie nennt man die Helfer aus Medina?",["Ansar","Muhadschirun","Quraisch"],"Ansar","medium",10,"Die Muslime aus Medina heißen Ansar."],
  [30,"Wie nennt man die Auswanderer aus Mekka?",["Muhadschirun","Ansar","Banu Hashim"],"Muhadschirun","medium",10,"Die Auswanderer aus Mekka heißen Muhadschirun."],
  [31,"Welche Schlacht war die erste große Schlacht der Muslime?",["Badr","Uhud","Khandaq"],"Badr","medium",10,"Die Schlacht von Badr war die erste große Schlacht der Muslime."],
  [32,"In welchem Monat findet das Fasten statt?",["Ramadan","Schawwal","Dhul-Hidscha"],"Ramadan","easy",5,"Muslime fasten im Monat Ramadan."],
  [33,"In welche Richtung beten Muslime?",["Zur Kaaba","Zum Berg Uhud","Zum Meer"],"Zur Kaaba","easy",5,"Muslime beten in Richtung der Kaaba."],
  [34,"Wie heißt die Gebetsrichtung?",["Qibla","Sunnah","Hadith"],"Qibla","medium",10,"Die Gebetsrichtung heißt Qibla."],
  [35,"Wie heißt die Reise des Propheten ﷺ von Mekka nach Jerusalem und in die Himmel?",["Isra und Mi'raj","Hidschra","Badr"],"Isra und Mi'raj","hard",15,"Isra und Mi'raj bezeichnet die besondere Nachtreise."],
  [36,"Welches Gebet wurde bei Isra und Mi'raj besonders festgelegt?",["Die fünf täglichen Gebete","Das Freitagsgebet allein","Das Eid-Gebet"],"Die fünf täglichen Gebete","medium",10,"Die fünf täglichen Gebete wurden bei dieser Reise besonders wichtig."],
  [37,"Wie heißt das Vorbild des Propheten ﷺ?",["Sunnah","Zakat","Qibla"],"Sunnah","easy",5,"Die Sunnah ist das Vorbild und die Lebensweise des Propheten ﷺ."],
  [38,"Wie nennt man Aussagen und Berichte über den Propheten ﷺ?",["Hadith","Tafsir","Fiqh"],"Hadith","easy",5,"Hadithe berichten über Worte, Taten und Eigenschaften des Propheten ﷺ."],
  [39,"Welche Eigenschaft war beim Propheten ﷺ besonders bekannt?",["Barmherzigkeit","Ungeduld","Stolz"],"Barmherzigkeit","easy",5,"Der Prophet ﷺ war für seine Barmherzigkeit bekannt."],
  [40,"Wie behandelte der Prophet ﷺ Kinder?",["Mit Liebe und Geduld","Mit Härte","Mit Gleichgültigkeit"],"Mit Liebe und Geduld","easy",5,"Der Prophet ﷺ zeigte Kindern Liebe, Respekt und Geduld."],
  [41,"Wie viele Töchter hatte der Prophet ﷺ?",["Vier","Zwei","Sechs"],"Vier","medium",10,"Der Prophet ﷺ hatte vier Töchter."],
  [42,"Wie hieß eine Tochter des Propheten ﷺ?",["Fatima","Maryam","Asiya"],"Fatima","easy",5,"Fatima رضي الله عنها war eine Tochter des Propheten ﷺ."],
  [43,"Wie hieß ein Enkel des Propheten ﷺ?",["Hasan","Bilal","Salman"],"Hasan","medium",10,"Hasan رضي الله عنه war ein Enkel des Propheten ﷺ."],
  [44,"Wie hieß ein weiterer Enkel des Propheten ﷺ?",["Husain","Talha","Zubair"],"Husain","medium",10,"Husain رضي الله عنه war ebenfalls ein Enkel des Propheten ﷺ."],
  [45,"Wer war die Mutter von Hasan und Husain?",["Fatima","Aischa","Hafsa"],"Fatima","medium",10,"Fatima رضي الله عنها war die Mutter von Hasan und Husain."],
  [46,"Wer war der Vater von Hasan und Husain?",["Ali","Umar","Abu Bakr"],"Ali","medium",10,"Ali رضي الله عنه war der Vater von Hasan und Husain."],
  [47,"Wie hieß der beste Freund und Begleiter des Propheten ﷺ bei der Hidschra?",["Abu Bakr","Abu Lahab","Abu Dschahl"],"Abu Bakr","easy",5,"Abu Bakr رضي الله عنه war ein enger Begleiter des Propheten ﷺ."],
  [48,"Wer wurde als erster Kalif nach dem Propheten ﷺ gewählt?",["Abu Bakr","Umar","Uthman"],"Abu Bakr","medium",10,"Abu Bakr رضي الله عنه wurde der erste Kalif."],
  [49,"Wie hieß der zweite Kalif?",["Umar","Ali","Talha"],"Umar","medium",10,"Umar ibn al-Khattab رضي الله عنه war der zweite Kalif."],
  [50,"Wie hieß der dritte Kalif?",["Uthman","Hamza","Abbas"],"Uthman","medium",10,"Uthman ibn Affan رضي الله عنه war der dritte Kalif."],
  [51,"Wie hieß der vierte Kalif?",["Ali","Bilal","Zaid"],"Ali","medium",10,"Ali ibn Abi Talib رضي الله عنه war der vierte Kalif."],
  [52,"Wer war Hamza رضي الله عنه?",["Der Onkel des Propheten ﷺ","Der Sohn des Propheten ﷺ","Der Vater des Propheten ﷺ"],"Der Onkel des Propheten ﷺ","medium",10,"Hamza رضي الله عنه war der Onkel des Propheten ﷺ."],
  [53,"Wie wurde Hamza رضي الله عنه bekannt?",["Als Löwe Allahs","Als erster Muezzin","Als Schreiber der Offenbarung"],"Als Löwe Allahs","hard",15,"Hamza رضي الله عنه wurde als Löwe Allahs bekannt."],
  [54,"Wer war Abu Lahab?",["Ein Gegner des Propheten ﷺ","Ein treuer Begleiter","Ein Muezzin"],"Ein Gegner des Propheten ﷺ","medium",10,"Abu Lahab war ein Gegner des Propheten ﷺ."],
  [55,"Wer war Abu Dschahl?",["Ein Gegner des Islam","Ein Sohn des Propheten ﷺ","Ein Engel"],"Ein Gegner des Islam","medium",10,"Abu Dschahl war ein bekannter Gegner des Islam."],
  [56,"Welche Stadt nahm den Propheten ﷺ nach der Hidschra auf?",["Medina","Taif","Damaskus"],"Medina","easy",5,"Medina nahm den Propheten ﷺ und die Muslime auf."],
  [57,"Wie hieß der Vertrag, der Frieden mit den Quraisch brachte?",["Hudaybiyya","Badr","Uhud"],"Hudaybiyya","hard",15,"Der Vertrag von Hudaybiyya war ein wichtiger Friedensvertrag."],
  [58,"Wie nennt man die Eroberung Mekkas?",["Fath Mekka","Hidschra","Mi'raj"],"Fath Mekka","hard",15,"Fath Mekka bedeutet die Eroberung oder Öffnung Mekkas."],
  [59,"Wie behandelte der Prophet ﷺ die Menschen bei der Eroberung Mekkas?",["Mit Vergebung","Mit Rache","Mit Strafe für alle"],"Mit Vergebung","medium",10,"Der Prophet ﷺ zeigte große Vergebung."],
  [60,"Welche heilige Stadt enthält die Kaaba?",["Mekka","Medina","Jerusalem"],"Mekka","easy",5,"Die Kaaba befindet sich in Mekka."],
  [61,"Wie oft sollen Muslime täglich beten?",["Fünfmal","Einmal","Zweimal"],"Fünfmal","easy",5,"Muslime beten fünfmal am Tag."],
  [62,"Welches Buch wurde dem Propheten Muhammad ﷺ offenbart?",["Der Quran","Die Thora","Die Psalmen"],"Der Quran","easy",5,"Der Quran wurde dem Propheten Muhammad ﷺ offenbart."],
  [63,"In welcher Sprache wurde der Quran offenbart?",["Arabisch","Deutsch","Persisch"],"Arabisch","easy",5,"Der Quran wurde auf Arabisch offenbart."],
  [64,"Was lehrte der Prophet ﷺ über Ehrlichkeit?",["Man soll ehrlich sein","Man soll lügen","Ehrlichkeit ist unwichtig"],"Man soll ehrlich sein","easy",5,"Der Prophet ﷺ lehrte Ehrlichkeit und Vertrauen."],
  [65,"Was lehrte der Prophet ﷺ über Eltern?",["Man soll sie respektieren","Man soll sie ignorieren","Man soll unhöflich sein"],"Man soll sie respektieren","easy",5,"Der Islam legt großen Wert auf Respekt gegenüber Eltern."],
  [66,"Was lehrte der Prophet ﷺ über Nachbarn?",["Man soll gut zu ihnen sein","Man soll sie stören","Man soll sie vergessen"],"Man soll gut zu ihnen sein","easy",5,"Der Prophet ﷺ betonte gutes Verhalten gegenüber Nachbarn."],
  [67,"Was sagte der Prophet ﷺ über Wissen?",["Wissen ist wichtig","Wissen ist verboten","Wissen braucht niemand"],"Wissen ist wichtig","easy",5,"Der Islam ermutigt Menschen, Wissen zu suchen."],
  [68,"Wie verhielt sich der Prophet ﷺ gegenüber Armen?",["Hilfsbereit und barmherzig","Unfreundlich","Gleichgültig"],"Hilfsbereit und barmherzig","easy",5,"Der Prophet ﷺ half armen und bedürftigen Menschen."],
  [69,"Was bedeutet Rahma?",["Barmherzigkeit","Reichtum","Reise"],"Barmherzigkeit","easy",5,"Rahma bedeutet Barmherzigkeit."],
  [70,"Was bedeutet Sabr?",["Geduld","Angst","Hunger"],"Geduld","easy",5,"Sabr bedeutet Geduld."],
  [71,"Was bedeutet Schukr?",["Dankbarkeit","Streit","Schlaf"],"Dankbarkeit","easy",5,"Schukr bedeutet Dankbarkeit."],
  [72,"Was bedeutet Tawhid?",["Der Glaube an die Einheit Allahs","Eine Reise","Ein Markt"],"Der Glaube an die Einheit Allahs","medium",10,"Tawhid bedeutet, an die Einheit Allahs zu glauben."],
  [73,"Was ist Zakat?",["Eine Pflichtabgabe für Bedürftige","Ein Gebirge","Ein Festessen"],"Eine Pflichtabgabe für Bedürftige","medium",10,"Zakat ist eine wichtige soziale Pflicht im Islam."],
  [74,"Was ist Hajj?",["Pilgerfahrt nach Mekka","Fasten im Ramadan","Ein tägliches Gebet"],"Pilgerfahrt nach Mekka","medium",10,"Hajj ist die Pilgerfahrt nach Mekka."],
  [75,"Wie heißt das Fest nach Ramadan?",["Eid al-Fitr","Eid al-Adha","Jumuah"],"Eid al-Fitr","easy",5,"Eid al-Fitr wird nach Ramadan gefeiert."],
  [76,"Wie heißt das Opferfest?",["Eid al-Adha","Eid al-Fitr","Laylat al-Qadr"],"Eid al-Adha","easy",5,"Eid al-Adha ist das Opferfest."],
  [77,"Welche Moschee wurde in Medina gebaut?",["Masjid an-Nabawi","Masjid al-Aqsa","Masjid al-Haram"],"Masjid an-Nabawi","medium",10,"Masjid an-Nabawi ist die Moschee des Propheten ﷺ in Medina."],
  [78,"Welche Moschee steht in Mekka?",["Masjid al-Haram","Masjid an-Nabawi","Quba-Moschee"],"Masjid al-Haram","medium",10,"Masjid al-Haram befindet sich in Mekka."],
  [79,"Welche Moschee gilt als erste Moschee im Islam?",["Quba-Moschee","Masjid al-Haram","Masjid al-Aqsa"],"Quba-Moschee","hard",15,"Die Quba-Moschee gilt als eine der ersten Moscheen im Islam."],
  [80,"Wo befindet sich Masjid al-Aqsa?",["Jerusalem","Mekka","Medina"],"Jerusalem","medium",10,"Masjid al-Aqsa befindet sich in Jerusalem."],
  [81,"Was ist ein Sahabi?",["Ein Gefährte des Propheten ﷺ","Ein Händler","Ein König"],"Ein Gefährte des Propheten ﷺ","medium",10,"Ein Sahabi ist ein Gefährte des Propheten ﷺ."],
  [82,"Was bedeutet Salawat?",["Segenswünsche für den Propheten ﷺ","Eine Stadt","Ein Kleidungsstück"],"Segenswünsche für den Propheten ﷺ","medium",10,"Salawat sind Segenswünsche für den Propheten ﷺ."],
  [83,"Was sagen Muslime nach dem Namen des Propheten Muhammad?",["Sallallahu alaihi wa sallam","Radiallahu anhu","Subhanahu wa ta'ala"],"Sallallahu alaihi wa sallam","medium",10,"Nach seinem Namen sagen Muslime ﷺ oder sallallahu alaihi wa sallam."],
  [84,"Was bedeutet ﷺ ungefähr?",["Allahs Segen und Frieden seien auf ihm","Allah ist groß","Im Namen Allahs"],"Allahs Segen und Frieden seien auf ihm","medium",10,"ﷺ bedeutet: Allahs Segen und Frieden seien auf ihm."],
  [85,"Wie alt wurde der Prophet Muhammad ﷺ?",["63 Jahre","50 Jahre","70 Jahre"],"63 Jahre","medium",10,"Der Prophet ﷺ wurde 63 Jahre alt."],
  [86,"In welcher Stadt starb der Prophet ﷺ?",["Medina","Mekka","Taif"],"Medina","medium",10,"Der Prophet ﷺ starb in Medina."],
  [87,"Wo befindet sich das Grab des Propheten ﷺ?",["In Medina","In Mekka","In Jerusalem"],"In Medina","medium",10,"Das Grab des Propheten ﷺ befindet sich in Medina."],
  [88,"Wie hieß die Abschiedspilgerfahrt des Propheten ﷺ?",["Hajjat al-Wada","Hidschra","Badr"],"Hajjat al-Wada","hard",15,"Die letzte Pilgerfahrt des Propheten ﷺ heißt Hajjat al-Wada."],
  [89,"Was betonte der Prophet ﷺ in seiner Abschiedspredigt?",["Gerechtigkeit und Respekt","Stolz und Reichtum","Streit und Rache"],"Gerechtigkeit und Respekt","medium",10,"Er betonte Gerechtigkeit, Verantwortung und Respekt."],
  [90,"Wie sollen Muslime dem Propheten ﷺ folgen?",["Durch seine Sunnah","Durch Unhöflichkeit","Durch Faulheit"],"Durch seine Sunnah","easy",5,"Muslime folgen dem Propheten ﷺ durch seine Sunnah."],
  [91,"Welche Eigenschaft passt besonders zum Propheten ﷺ?",["Geduld","Arroganz","Ungerechtigkeit"],"Geduld","easy",5,"Der Prophet ﷺ zeigte große Geduld."],
  [92,"Wie sollte man nach dem Vorbild des Propheten ﷺ sprechen?",["Freundlich und wahrhaftig","Laut und verletzend","Unhöflich"],"Freundlich und wahrhaftig","easy",5,"Der Prophet ﷺ sprach freundlich, ehrlich und respektvoll."],
  [93,"Was mochte der Prophet ﷺ im Verhalten der Menschen?",["Gute Charaktereigenschaften","Lügen","Ungerechtigkeit"],"Gute Charaktereigenschaften","easy",5,"Der Prophet ﷺ legte großen Wert auf guten Charakter."],
  [94,"Wie nennt man den guten Charakter im Islam?",["Akhlaq","Hidschra","Qibla"],"Akhlaq","medium",10,"Akhlaq bedeutet Charakter oder gutes Verhalten."],
  [95,"Was ist eine wichtige Lehre des Propheten ﷺ für Kinder?",["Respekt und Freundlichkeit","Streit und Lügen","Faulheit"],"Respekt und Freundlichkeit","easy",5,"Kinder lernen vom Propheten ﷺ Respekt, Freundlichkeit und Ehrlichkeit."],
  [96,"Wie sollen Muslime mit Tieren umgehen?",["Barmherzig","Grausam","Gleichgültig"],"Barmherzig","easy",5,"Der Prophet ﷺ lehrte Barmherzigkeit gegenüber Tieren."],
  [97,"Wie sollen Muslime mit der Natur umgehen?",["Verantwortungsvoll","Verschwenderisch","Schädlich"],"Verantwortungsvoll","easy",5,"Muslime sollen verantwortungsvoll mit Allahs Schöpfung umgehen."],
  [98,"Was ist eine wichtige Sunnah beim Essen?",["Mit Bismillah beginnen","Essen verschwenden","Nicht teilen"],"Mit Bismillah beginnen","easy",5,"Es gehört zur Sunnah, vor dem Essen Bismillah zu sagen."],
  [99,"Was ist eine wichtige Sunnah nach dem Essen?",["Allah danken","Sich beschweren","Essen wegwerfen"],"Allah danken","easy",5,"Nach dem Essen soll man Allah danken."],
  [100,"Warum lernen Muslime über den Propheten Muhammad ﷺ?",["Um seinem guten Vorbild zu folgen","Um nur Geschichte zu lernen","Um andere zu kritisieren"],"Um seinem guten Vorbild zu folgen","easy",5,"Muslime lernen über den Propheten ﷺ, um seinem schönen Vorbild zu folgen."]
].map(([id, question, options, correctAnswer, difficulty, hasnat, explanation]) => ({
  id, question, options, correctAnswer, difficulty, hasnat, explanation
}));
